#
# Copyright (C) Dmitry Volyntsev
# Copyright (C) NGINX, Inc.
#

proc njs_test {body {opts ""}} {

    if {$opts eq ""} {
        spawn  -nottycopy njs

    } else {
        spawn  -nottycopy njs $opts
    }

    expect -re "interactive njs \\d+\.\\d+\.\\d+\r\n\r"
    expect "v.<Tab> -> the properties and prototype methods of v.\r
type console.help() for more information\r
\r
>> "

    set len [llength $body]
    for {set i 0} {$i < $len} {incr i} {
        set pair [lindex $body $i]
        send [lindex $pair 0]
        expect [lindex $pair 1]
    }

    # Ctrl-C
    send \x03
    expect eof
}

proc njs_run {opts output} {
    spawn  -nottycopy njs $opts
    expect -re $output
    expect eof
}

njs_test {
    {"njs.version\r\n"
     "njs.version\r\n\*\.\*\.\*"}
}

# simple multi line interation
njs_test {
    {"var a = 1\r\n"
     "var a = 1\r\nundefined\r\n>> "}
    {"a *= 2\r\n"
     "a *= 2\r\n2\r\n>> "}
}

# Global completions, no
njs_test {
    {"\t\tn"
     "\a\r\nDisplay all*possibilities? (y or n)*>> "}
}

# Global completions, yes
njs_test {
    {"\t\ty"
     "\a\r\nDisplay all*possibilities? (y or n)*await"}
}

# Global completions, single partial match
njs_test {
    {"O\t"
     "O\abject"}
}

njs_test {
    {"Ma\t"
     "Ma\ath"}
}

njs_test {
    {"conso\t"
     "conso\ale"}
}

# Global completions, multiple partial match
njs_test {
    {"cons\t\t"
     "console*console.help*console.time*const"}
}

njs_test {
    {"O\t"
     "O\abject"}
    {".\t\t"
     "Object.create*Object.isSealed"}
}

njs_test {
    {"Object.\t\t"
     "Object.create*Object.isSealed"}
}

njs_test {
    {"Object.g\t"
     "Object.g\aet"}
    {"\t"
     "Object.getOwnPropertyDescriptor*Object.getPrototypeOf"}
}

njs_test {
    {"Ma\t"
     "Ma\ath"}
    {".\t\t"
     "Math.__proto__*Math.cbrt*Math.fround*Math.log2"}
}

# Global completions, no matches
njs_test {
    {"1.\t\t"
     "1."}
}

njs_test {
    {"1..\t\t"
     "1.."}
}

njs_test {
    {"'abc'.\t\t"
     "'abc'."}
}

# Global completions, global vars
njs_test {
    {"var a = 1; var aa = 2\r\n"
     "var a = 1; var aa = 2\r\nundefined\r\n>> "}
    {"a\t\t"
     "a*aa*arguments*await"}
}

njs_test {
    {"var zz = 1\r\n"
     "var zz = 1\r\nundefined\r\n>> "}
    {"1 + z\t\r\n"
     "1 + zz\r\n2"}
}

njs_test {
    {"unknown_var\t\t"
     "unknown_var"}
}

njs_test {
    {"unknown_var.\t\t"
     "unknown_var."}
}

# An object's level completions
njs_test {
    {"var o = {zz:1, zb:2}\r\n"
     "var o = {zz:1, zb:2}\r\nundefined\r\n>> "}
    {"o.z\t\t"
     "o.zb*o.zz"}
}

njs_test {
    {"var d = new Date()\r\n"
     "var d = new Date()\r\nundefined\r\n>> "}
    {"d.to\t\t"
     "d.toDateString*d.toLocaleDateString*d.toString"}
}

njs_test {
    {"var o = {a:new Date()}\r\n"
     "var o = {a:new Date()}\r\nundefined\r\n>> "}
    {"o.a.to\t\t"
     "o.a.toDateString*o.a.toLocaleDateString*o.a.toString"}
}

# function declarations in interactive mode
njs_test {
    {"function a() { return 1; }\r\n"
     "undefined\r\n>> "}
    {"a();\r\n"
     "1\r\n>> "}
    {"function a() { return 2; }\r\n"
     "undefined\r\n>> "}
    {"a();\r\n"
     "2\r\n>> "}
}

# console object
njs_test {
    {"console.log()\r\n"
     "console.log()\r\nundefined\r\n>> "}
    {"console.log(1)\r\n"
     "console.log(1)\r\n1\r\nundefined\r\n>> "}
    {"console.log(1, 'a')\r\n"
     "console.log(1, 'a')\r\n1 'a'\r\nundefined\r\n>> "}
    {"console.dump()\r\n"
     "console.dump()\r\nundefined\r\n>> "}
    {"console.dump(1)\r\n"
     "console.dump(1)\r\n1\r\nundefined\r\n>> "}
    {"console.dump(1, 'a')\r\n"
     "console.dump(1, 'a')\r\n1 'a'\r\nundefined\r\n>> "}
    {"console.help()\r\n"
     "console.help()\r\nVM built-in objects:"}
}

# console.time* functions
njs_test {
    {"console.time()\r\n"
     "console.time()\r\nundefined\r\n>> "}
    {"console.time(undefined)\r\n"
     "console.time(undefined)\r\nundefined\r\n>> "}
    {"console.timeEnd()\r\n"
     "console.timeEnd()\r\ndefault: *.*ms\r\nundefined\r\n>> "}
    {"console.time('a')\r\n"
     "console.time('a')\r\nError: labels not implemented"}
    {"console.timeEnd('a')\r\n"
     "console.timeEnd('a')\r\nError: labels not implemented"}
    {"console.timeEnd()\r\n"
     "console.timeEnd()\r\nTimer \"default\" doesn’t exist."}
}

njs_test {
    {"console.ll()\r\n"
     "console.ll()\r\nTypeError: \"ll\" is not a function"}
}

njs_test {
    {"console.log.length\r\n"
     "console.log.length\r\n0"}
}

njs_test {
    {"var print = console.log.bind(console); print(1, 'a', [1, 2])\r\n"
     "1 'a' \\\[1,2]\r\nundefined\r\n>> "}
    {"var print = console.dump.bind(console); print(1, 'a', [1, 2])\r\n"
     "1 'a' \\\[\r\n 1,\r\n 2\r\n]\r\nundefined\r\n>> "}
}

# Backtraces for external objects
njs_test {
    {"console.log(console.a.a)\r\n"
     "console.log(console.a.a)\r\nTypeError:*at console.log (native)"}
}

# dumper
njs_test {
    {"var o = {toString: function(){}, log: console.log}\r\n"
     "undefined\r\n>> "}
    {"o\r\n"
     "o\r\n{\r\n toString: \\\[Function],\r\n log: \\\[Function: native]\r\n}"}
}

njs_test {
    {"[1, new Number(2), 'a', new String('αβZγ'), true, new Boolean(false)]\r\n"
     "\\\[\r\n 1,\r\n \\\[Number: 2],\r\n 'a',\r\n \\\[String: 'αβZγ'],\r\n true,\r\n \\\[Boolean: false]\r\n]"}
}

njs_test {
    {"[undefined,,null]\r\n"
     "\\\[\r\n undefined,\r\n <empty>,\r\n null\r\n]"}
}

njs_test {
    {"[InternalError(),TypeError('msg'), new RegExp(), /^undef$/m, new Date(0)]\r\n"
     "\\\[\r\n InternalError,\r\n TypeError: msg,\r\n /(?:)/,\r\n /^undef$/m,\r\n 1970-01-01T00:00:00.000Z\r\n]"}
}

# dumper excapes special characters as JSON.stringify()
# except '\"'
njs_test {
    {"\"\\r\\0\\\"\"\r\n"
     "'\\\\r\\\\u0000\"'"}
}

njs_test {
    {"[{a:1}]\r\n"
     "\r\n\\\[\r\n {\r\n  a: 1\r\n }\r\n]"}
}

# Backtraces are reset between invocations
njs_test {
    {"JSON.parse(Error())\r\n"
     "JSON.parse(Error())\r\nSyntaxError: Unexpected token at position 0*at JSON.parse (native)"}
    {"JSON.parse(Error()\r\n"
     "JSON.parse(Error()\r\nSyntaxError: Unexpected token \"\" in shell:1"}
}

njs_test {
    {"try { console.log({ toString: function() { throw 'test'; } }) } catch (e) {}\r\n"
     "undefined"}
    {"function f() { throw 't' }; try { console.log({ toString: function() { return f() } }) } catch (e) {}\r\n"
     "undefined"}
}

njs_test {
    {"(function() { throw 'test' })()\r\n"
     "test\r\n    at anonymous (shell:1)"}
}

# Non-ASCII characters
njs_test {
    {"'絵文字'\r\n"
     "'絵文字'"}
    {"var v = 'абвгдеёжзийкл';v[10]\r\n"
     "'й'"}
}

# Immediate events

njs_test {
    {"var t = setImmediate(console.log, 'a', 'aa')\r\n"
     "undefined\r\n'a' 'aa'"}
}

njs_test {
    {"var a = 1 + 1; setTimeout(function (x) {a = x}, 0, 'a'); a\r\n"
     "2"}
    {"a\r\n"
     "a\r\n'a'"}
}

njs_test {
    {"setTimeout(function () {}, 1, 'a')\r\n"
     "njs_console_set_timer(): async timers unsupported"}
}

njs_test {
    {"var a = 1 + 1; setTimeout(function (x) { setTimeout(function (y) {a = y}, 0, x)}, 0, 'a'); a\r\n"
     "2"}
    {"a\r\n"
     "a\r\n'a'"}
}

njs_test {
    {"var a = 1 + 1; setImmediate(function (x) { setImmediate(function (y) {a = y}, x)}, 'a'); a\r\n"
     "2"}
    {"a\r\n"
     "a\r\n'a'"}
}

njs_test {
    {"var i = 0; (function x() { if (i < 10) setImmediate(x); i++; })()\r\n"
     "undefined"}
    {"i\r\n"
     "i\r\n11"}
}

njs_test {
    {"var a = 0, t = setImmediate(function() {a = 1}); clearTimeout(t)\r\n"
     "undefined"}
    {"a\r\n"
     "a\r\n0"}
}

njs_test {
    {"var i = 0; (function x() { if (i < 3) setImmediate(x); i++; throw 'Oops';})()\r\n"
     "Oops"}
    {"i\r\n"
     "i\r\n4"}
}

njs_test {
    {"var i = 0, queue = []; (function x() { if (i < 5) setImmediate(x); queue.push(i++); })()\r\n"
     "undefined"}
    {"queue.toString()\r\n"
     "queue.toString()\r\n'0,1,2,3,4,5'"}
}

# require('fs')

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.read\t"
     "fs.read\aFile"}
}

# require('fs').readFile()

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFile('njs/test/fs/utf8', 'utf8', function (e, data) {console.log(data[2]+data.length)})\r\n"
     "'Z4'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFile('njs/test/fs/utf8', function (e, data) {console.log(data[4]+data.length)})\r\n"
     "'Z7'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFile('njs/test/fs/utf8', {encoding:'utf8',flag:'r+'}, function (e, data) {console.log(data)})\r\n"
     "'αβZγ'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFile('njs/test/fs/ascii', function (e, data) {console.log(data[599])})\r\n"
     "'x'\r\nundefined\r\n>> "}
    {"fs.readFile('njs/test/fs/ascii', {encoding:'utf8',flag:'r+'}, function (e, data) {console.log(data[599])})\r\n"
     "'x'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs'); \r\n"
     "undefined\r\n>> "}
    {"fs.readFile('njs/test/fs/nonexistent', 'utf8', function (e) {console.log(JSON.stringify(e))})\r\n"
     "'{\"errno\":2,\"path\":\"njs/test/fs/nonexistent\",\"syscall\":\"open\"}'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs'); \r\n"
     "undefined\r\n>> "}
    {"fs.readFile('njs/test/fs/nonexistent', {encoding:'utf8', flag:'r+'}, function (e) {console.log(e)})\r\n"
     "Error: No such file or directory\r\nundefined\r\n>> "}
}

# require('fs').readFileSync()

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs/test/fs/utf8').toString('base64')\r\n"
     "'zrHOslrOsw=='\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs/test/fs/utf8', 'utf8')[2]\r\n"
     "'Z'\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs/test/fs/utf8')[4]\r\n"
     "'Z'\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs/test/fs/utf8', {encoding:'utf8',flag:'r+'})\r\n"
     "'αβZγ'\r\n>> "}
}

njs_test {
    {"var fs = require('fs'), fn = 'njs/test/fs/ascii'\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync(fn)[599] + fs.readFileSync(fn, 'utf8')[599]\r\n"
     "'xx'\r\n>> "}
}

njs_test {
    {"var fs = require('fs'); \r\n"
     "undefined\r\n>> "}
    {"try { fs.readFileSync('njs/test/fs/nonexistent')} catch (e) {console.log(JSON.stringify(e))}\r\n"
     "'{\"errno\":2,\"path\":\"njs/test/fs/nonexistent\",\"syscall\":\"open\"}'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs/test/fs/non_utf8').charCodeAt(1)\r\n"
     "128"}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs/test/fs/non_utf8', 'utf8')\r\n"
     "Error: Non-UTF8 file, convertion is not implemented"}
}


# require('fs').writeFile()

exec rm -fr njs_test_file2

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"function h1(e) {if (e) {throw e}; console.log(fs.readFileSync('njs_test_file2'))}\r\n"
     "undefined\r\n>> "}
    {"fs.writeFile('njs_test_file2', 'ABC', h1)\r\n"
     "'ABC'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFile('njs_test_file2', 'ABC', 'utf8', function (e) { if (e) {throw e}; console.log(fs.readFileSync('njs_test_file2'))})\r\n"
     "'ABC'\r\nundefined\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFile('njs_test_file2', 'ABC', {encoding:'utf8', mode:0o666}, function (e) { if (e) {throw e}; console.log(fs.readFileSync('njs_test_file2'))})\r\n"
     "'ABC'\r\nundefined\r\n>> "}
}

exec rm -fr njs_wo_file

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFile('njs_wo_file', 'ABC', {mode:0o222}, function (e) {console.log(fs.readFileSync('njs_wo_file'))})\r\n"
     "Error: Permission denied"}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFile('/invalid_path', 'ABC', function (e) { console.log(JSON.stringify(e))})\r\n"
     "'{\"errno\":13,\"path\":\"/invalid_path\",\"syscall\":\"open\"}'\r\nundefined\r\n>> "}
}

# require('fs').writeFileSync()

exec rm -fr njs_test_file2

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFileSync('njs_test_file2', 'ABC')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs_test_file2')\r\n"
     "'ABC'\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFileSync('njs_test_file2', 'ABC', 'utf8')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs_test_file2')\r\n"
     "'ABC'\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFileSync('njs_test_file2', 'ABC')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFileSync('njs_test_file2', 'ABC')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs_test_file2')\r\n"
     "'ABC'\r\n>> "}
}

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFileSync('njs_test_file2', 'ABC', {encoding:'utf8', mode:0o666})\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs_test_file2')\r\n"
     "'ABC'\r\n>> "}
}

exec rm -fr njs_wo_file

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.writeFileSync('njs_wo_file', 'ABC', {mode:0o222}); fs.readFileSync('njs_wo_file')\r\n"
     "Error: Permission denied"}
}

# require('fs').appendFile()

exec rm -fr njs_test_file2

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"function h1(e) {console.log(fs.readFileSync('njs_test_file2'))}\r\n"
     "undefined\r\n>> "}
    {"function h2(e) {fs.appendFile('njs_test_file2', 'ABC', h1)}\r\n"
     "undefined\r\n>> "}
    {"fs.appendFile('njs_test_file2', 'ABC', h2)\r\n"
     "'ABCABC'\r\nundefined\r\n>> "}
}

# require('fs').appendFileSync()

exec rm -fr njs_test_file2

njs_test {
    {"var fs = require('fs')\r\n"
     "undefined\r\n>> "}
    {"fs.appendFileSync('njs_test_file2', 'ABC')\r\n"
     "undefined\r\n>> "}
    {"fs.appendFileSync('njs_test_file2', 'ABC')\r\n"
     "undefined\r\n>> "}
    {"fs.readFileSync('njs_test_file2')\r\n"
     "'ABCABC'\r\n>> "}
}

# CLI OPTIONS

# help

njs_run "-h" "Interactive njs shell.\r\n\r\nOptions:"

# version

njs_run "-v" "\\d+\.\\d+\.\\d+"

# disassemble

njs_test {
    {"1+1\r\n"
     "00000 ADD*\r\n00040 STOP*\r\n\r\n2"}
    {"for (var n in [1]) {try {break} finally{}}\r\n"
     "00000 ARRAY*\r\n*TRY BREAK*STOP*\r\n\r\nundefined"}
    {"(function() {try {return} finally{}})()\r\n"
     "00000 TRY START*\r\n*TRY RETURN*STOP*\r\n\r\nundefined"}
} "-d"

# sandboxing

njs_test {
    {"var fs = require('fs')\r\n"
     "Error: Cannot find module \"fs\"\r\n"}
} "-s"

njs_test {
    {"var crypto = require('crypto')\r\n"
     "undefined\r\n"}
} "-s"
