name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  buildbot:
    uses: nginx/ci-self-hosted/.github/workflows/njs-buildbot.yml@a18ba87ce844172e745b83b6bcfed902c5bbe039 # main
